item {
  id: 1
  name: 'airspeed'
}
item {
  id: 2
  name: 'altimeter'
}
item {
  id: 3
  name: 'verticalSpeed'
}
item {
  id: 4
  name: 'attitude'
}
item {
  id: 5
  name: 'horizontalSituation'
}


